### ISSUE TITLE
Создание проекта падает с ошибкой

### ISSUE THREAD

**Issue by Sovent** [LeagueOfDevelopers/LodCore#192]
https://api.lod-misis.ru/github/callback/repositories/13/collaborators?ids=%5B%5D&frontend_callback=https://lod-misis.ru/admin/projects/add?action=add_collaborator&code=94190aff8056eb4bc09c&state=6v9tKTmyGki0BiKsmOK8IQ
вот по этому урлу выдаётся такая ошибка 
{"$id":"1","Message":"An error has occurred."}

**Comment by Helenga** [comment]
Ошибка связана с #193 и #194 issues и не может быть воспроизведена
