### ISSUE TITLE
Найди библиотеку для транслитерации русского текста

### ISSUE THREAD

**Issue by Sovent** [LeagueOfDevelopers/LodCore#26]
Для того, чтобы делать идентификаторы проектов Redmine латиницей

**Comment by IPRIT** [comment]
В c# для этого нужна библиотека?

**Comment by Sovent** [comment]
Ну, в стандартных библиотеках я ничего такого не видел.

**Comment by IPRIT** [comment]
@Sovent, https://github.com/AlexanderBrevig/String.Latinize

**Comment by Sovent** [comment]
Да я уже Unidecode нашёл, спасибо
